import { pick } from "./pick";
import { Question, generateForward, generateBackward, Pairs } from "./questions";

const qcodes: Pairs = [
   ["QRA?", "What is the name (or call sign) of your station?"],
   ["QRA", "The name (or call sign) of my station is ..."],
   ["QRB?", "How far are you from my station?"],
   ["QRB", "The distance between our stations is ... nautical miles (or km)."],
   ["QRG?", "Will you tell me my exact frequency (or that of ...)?"],
   ["QRG", "Your exact frequency (or that of ... ) is ... kHz (or MHz)."],
   ["QRH?", "Does my frequency vary?"],
   ["QRH", "Your frequency varies."],
   ["QRI?", "How is the tone of my transmission?"],
   ["QRI", "The tone of your transmission is (1: good, 2: variable 3: bad)"],
   ["QRK?", "What is the readability of my signals (or those of ...)?"],
   ["QRK", "The readability of your signals (or those of ...) is ... (1: bad .. 5: excellent)."],
   ["QRL?", "Are you busy?"],
   ["QRL", "I am busy. (or I am busy with ... ) Please do not interfere."],
   ["QRM?", "Do you have interference?"],
   ["QRM", "I have interference."],
   ["QRN?", "Are you troubled by static noise?"],
   ["QRN", "I am troubled by static noise."],
   ["QRO?", "Shall I increase transmit power?"],
   ["QRO", "Please increase transmit power."],
   ["QRP?", "Shall I decrease transmit power?"],
   ["QRP", "Please decrease transmit power."],
   ["QRQ?", "Shall I send faster?"],
   ["QRQ", "Please send faster (... words per minute)."],
   ["QRS?", "Shall I send more slowly?"],
   ["QRS", "Please send more slowly (... words per minute)."],
   ["QRT?", "Shall I cease or suspend operation?"],
   ["QRT", "I am suspending operation."],
   ["QRU?", "Have you anything for me?"],
   ["QRU", "I have nothing for you."],
   ["QRV?", "Are you ready?"],
   ["QRV", "I am ready."],
   ["QRX?", "Shall I standby? / When will you call me again?"],
   ["QRX", "Please standby. / I will call you again at ... (hours) on ... kHz (or MHz)."],
   ["QRZ?", "Who is calling me?"],
   ["QRZ", "You are being called by ... (on ... kHz (or MHz))."],
   ["QSA?", "What is the strength of my signals (or those of ... )?"],
   ["QSA", "The strength of your signals (or those of ...) is ... (1: very weak .. 5: very strong)."],
   ["QSB?", "Are my signals fading?"],
   ["QSB", "Your signals are fading."],
   ["QSD?", "Is my keying defective?"],
   ["QSD", "Your keying is defective."],
   ["QSK?", "Can you hear me between your signals (while transmitting), and if so can I break in on your transmission?"],
   ["QSK", "I can hear you between my signals (while transmitting); break in on my transmission."],
   ["QSL?", "Can you acknowledge receipt?"],
   ["QSL", "I am acknowledging receipt."],
   ["QSM?", "Shall I repeat the last telegram (message) which I sent you, or some previous telegram (message)?"],
   ["QSM", "Repeat the last telegram (message) which you sent me (or telegram(s) (message(s)) numbers(s) ...)."],
   ["QSN?", "Did you hear me (or ...) on ... kHz (or MHz)?."],
   ["QSN", "I did hear you (or ...) on ... kHz (or MHz)."],
   ["QSO?", "Can you communicate with ... direct or by relay?"],
   ["QSO", "I can communicate with ... direct (or by relay through ...)."],
   ["QSP?", "Will you relay a message to ...?"],
   ["QSP", "I will relay a message to ... ."],
   ["QSS?", "What working frequency will you use?"],
   ["QSS", "I will use ... kHz (or MHz)."],
   ["QSU?", "Shall I send or reply on this frequency (or on ... kHz (or MHz))?"],
   ["QSU", "Please send or reply on this frequency (or on ... kHz (or MHz))."],
   ["QSV?", "Shall I send a series of \"V\" on this frequency (or on ... kHz (or MHz))?"],
   ["QSV", "Please send a series of \"V\" on this frequency (or on ... kHz (or MHz))."],
   ["QSX?", "Will you listen to ... on ... kHz (or MHz)?"],
   ["QSX", "I am listening to ... on ... kHz (or MHz)."],
   ["QSY?", "Shall I change transmission frequency (to ... kHz (or MHz))?"],
   ["QSY", "Please change transmission frequency (to ... kHz (or MHz))."],
   ["QSZ?", "Shall I send each word or group more than once?"],
   ["QSZ", "Send each word or group twice (or ... times)."],
   ["QTC?", "How many telegrams (messages) have you to send?"],
   ["QTC", "I have ... telegrams (messages) for you (or for ...)."],
   ["QTH?", "What is your position in latitude and longitude (or according to any other indication)?"],
   ["QTH", "My position is ... latitude, ... longitude."],
   ["QTR?", "What is the correct time?"],
   ["QTR", "The correct time is ... hours."],
];


export function generateQuestion(): Question {
    const topic = "Q-codes";
    const source = "https://www.giangrandi.org/electronics/radio/qcode.shtml";
    const generator = pick([
        () => generateForward(topic, source, st => `Translate '${st}'`, qcodes),
        () => generateBackward(topic, source, st => st, qcodes),
    ]);
    return generator();
}